// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-DfTRCzDiFPkMCaxO3B3nk9gxZdwYT0',
    appId: '1:569208185945:web:466959d83e3c93b507bd48',
    messagingSenderId: '569208185945',
    projectId: 'kiitsap-notification',
    authDomain: 'kiitsap-notification.firebaseapp.com',
    storageBucket: 'kiitsap-notification.firebasestorage.app',
    measurementId: 'G-1Z7E726W0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-A8RpfFXWEtAirfSRKxM0gXRqmz-EAM0',
    appId: '1:569208185945:android:4d964917c2dcff0907bd48',
    messagingSenderId: '569208185945',
    projectId: 'kiitsap-notification',
    storageBucket: 'kiitsap-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4ZaO1nL4IiVKmxg96C5srsB-h5iVaE8',
    appId: '1:569208185945:ios:21e96d73165c407007bd48',
    messagingSenderId: '569208185945',
    projectId: 'kiitsap-notification',
    storageBucket: 'kiitsap-notification.firebasestorage.app',
    iosBundleId: 'com.example.sapPortalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV4ZaO1nL4IiVKmxg96C5srsB-h5iVaE8',
    appId: '1:569208185945:ios:5415bf66f02d43d407bd48',
    messagingSenderId: '569208185945',
    projectId: 'kiitsap-notification',
    storageBucket: 'kiitsap-notification.firebasestorage.app',
    iosBundleId: 'no',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW-DfTRCzDiFPkMCaxO3B3nk9gxZdwYT0',
    appId: '1:569208185945:web:28b0b72bdfec0d2907bd48',
    messagingSenderId: '569208185945',
    projectId: 'kiitsap-notification',
    authDomain: 'kiitsap-notification.firebaseapp.com',
    storageBucket: 'kiitsap-notification.firebasestorage.app',
    measurementId: 'G-HZ3KQ6HZ4G',
  );
}
